// flow-typed signature: a43ba1c0f84b9ea420bece6c52950462
// flow-typed version: <<STUB>>/babel-preset-es2015_v6.6.0/flow_v0.33.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-preset-es2015'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-preset-es2015' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'babel-preset-es2015/index' {
  declare module.exports: $Exports<'babel-preset-es2015'>;
}
declare module 'babel-preset-es2015/index.js' {
  declare module.exports: $Exports<'babel-preset-es2015'>;
}
